#!/usr/bin/env python3.11
"""
hook-stop-autocommit.py — Auto-commit uncommitted session work on Stop.

Best-effort: if the terminal is killed before this runs, recall catches it
at next session start via detect-uncommitted.py.

Behavior:
1. Check git status for untracked/modified files
2. Filter to session-relevant paths (primitives, tasks, scripts, tests, skills, config, docs, stores)
3. If changes found, write a minimal session-log entry and commit everything
4. Skip: .env, secrets, debug logs, __pycache__, .claude/worktrees
"""

import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

REPO = Path(__file__).resolve().parent.parent
SESSION_LOG = REPO / "tasks" / "session-log.md"
CURRENT_STATE = REPO / "docs" / "current-state.md"
PACIFIC = ZoneInfo("America/Los_Angeles")

# Paths worth auto-committing
RELEVANT_PREFIXES = [
    "tasks/", "scripts/", "tests/", "skills/",
    "config/", "docs/", "stores/baseline/", ".claude/rules/",
    ".claude/skills/",
]

# Paths to never stage
EXCLUDE_PATTERNS = [
    ".env", "cos_debug", "__pycache__", ".claude/worktrees/",
    "node_modules/", ".DS_Store", "*.pyc", "*.log",
]


def git(*args, **kwargs):
    result = subprocess.run(
        ["git", "-C", str(REPO)] + list(args),
        capture_output=True, text=True, timeout=10, **kwargs,
    )
    return result.stdout.strip(), result.returncode


def is_relevant(path):
    for pattern in EXCLUDE_PATTERNS:
        if pattern in path:
            return False
    for prefix in RELEVANT_PREFIXES:
        if path.startswith(prefix):
            return True
    return False


def get_uncommitted_files():
    # Modified (staged + unstaged)
    out, _ = git("diff", "--name-only", "HEAD")
    modified = [f for f in (out or "").splitlines() if f.strip()]

    # Staged
    out, _ = git("diff", "--cached", "--name-only")
    staged = [f for f in (out or "").splitlines() if f.strip()]

    # Untracked
    out, _ = git("status", "--porcelain")
    untracked = []
    for line in (out or "").splitlines():
        if line.startswith("??"):
            untracked.append(line[3:].strip())

    all_files = list(set(modified + staged + untracked))
    return sorted([f for f in all_files if is_relevant(f)])


def write_session_log_entry(files):
    now = datetime.now(PACIFIC)
    date_str = now.strftime("%Y-%m-%d")

    categories = {}
    for f in sorted(files):
        cat = f.split("/")[0] if "/" in f else "root"
        categories.setdefault(cat, []).append(f)

    lines = [
        "",
        "---",
        "",
        f"## {date_str} — [auto-captured: session ended without /wrap-session]",
        "",
        "**Note:** This entry was auto-generated by the Stop hook because the session",
        "ended without running `/wrap-session`. Review and enrich in the next session.",
        "",
        "**Files changed (uncommitted):**",
    ]
    for cat, cat_files in categories.items():
        lines.append(f"- **{cat}/**: {', '.join(Path(f).name for f in cat_files)}")

    lines.append("")
    lines.append(f"**Auto-committed:** {now.strftime('%Y-%m-%d %H:%M PT')}")
    lines.append("")

    entry = "\n".join(lines)

    if SESSION_LOG.exists():
        content = SESSION_LOG.read_text()
        SESSION_LOG.write_text(content + entry)
    else:
        SESSION_LOG.write_text("# Session Log\n" + entry)


def mark_current_state_stale(files):
    """Inject a staleness warning into current-state.md so recall doesn't trust frozen Next Action."""
    if not CURRENT_STATE.exists():
        return
    content = CURRENT_STATE.read_text()
    if "## ⚠ STALE" in content:
        return  # already marked

    now = datetime.now(PACIFIC)
    categories = set()
    for f in files:
        categories.add(f.split("/")[0] if "/" in f else "root")

    warning = (
        f"\n## ⚠ STALE — auto-captured session ended without /wrap-session\n"
        f"**Auto-capture date:** {now.strftime('%Y-%m-%d %H:%M PT')}\n"
        f"**Files changed this session:** {len(files)} files in {', '.join(sorted(categories))}\n"
        f"**WARNING:** The \"Next Action\" below may be outdated. "
        f"Cross-check with `git log --oneline -10` and recent session-log entries.\n"
    )

    lines = content.split("\n")
    # Insert after the first header line
    insert_at = 1 if len(lines) > 0 else 0
    lines.insert(insert_at, warning)
    CURRENT_STATE.write_text("\n".join(lines))


DEDUP_WINDOW_SECS = 600  # 10 minutes


def last_commit_is_recent_auto():
    """Check if the last commit is an [auto] commit within the dedup window."""
    subject, rc = git("log", "-1", "--format=%s")
    if rc != 0 or not subject.startswith("[auto]"):
        return False
    epoch_str, rc = git("log", "-1", "--format=%ct")
    if rc != 0:
        return False
    try:
        commit_age = time.time() - int(epoch_str)
        return commit_age < DEDUP_WINDOW_SECS
    except ValueError:
        return False


def main():
    files = get_uncommitted_files()
    if not files:
        print("stop-autocommit: no uncommitted session work")
        return

    # Skip noise: single leftover files (e.g. a deletion) aren't worth an auto-commit.
    # The next session's detect-uncommitted.py will catch them anyway.
    if len(files) < 3:
        print(f"stop-autocommit: only {len(files)} files, skipping (detect-uncommitted will catch at next session)")
        return

    amend = last_commit_is_recent_auto()
    verb = "amending" if amend else "auto-committing"
    print(f"stop-autocommit: {len(files)} uncommitted files detected, {verb}")

    # Only write a new session-log entry on fresh commits (not amends)
    if not amend:
        write_session_log_entry(files)

    # Mark current-state.md as stale
    try:
        mark_current_state_stale(files)
    except Exception as e:
        print(f"stop-autocommit: mark-stale failed (non-fatal): {e}", file=sys.stderr)

    # Stage all relevant files
    for f in files:
        full = REPO / f
        if full.exists():
            git("add", f)

    # Also stage the session log and current-state we just updated
    git("add", "tasks/session-log.md")
    if CURRENT_STATE.exists():
        git("add", "docs/current-state.md")

    # Commit (amend if recent [auto] exists, otherwise new commit)
    now = datetime.now(PACIFIC)
    msg = (
        f"[auto] Session work captured {now.strftime('%Y-%m-%d %H:%M PT')}\n"
        f"\n"
        f"{len(files)} files from session that ended without /wrap-session.\n"
        f"Review and enrich session log entry in next session.\n"
        f"\n"
        f"Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>"
    )

    commit_args = ["commit", "-m", msg]
    if amend:
        commit_args = ["commit", "--amend", "-m", msg]

    out, rc = git(*commit_args)
    if rc == 0:
        action = "amended into previous" if amend else "committed"
        print(f"stop-autocommit: {action} ({len(files)} files)")
    else:
        print(f"stop-autocommit: commit failed: {out}", file=sys.stderr)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        # Best-effort — never block session close
        print(f"stop-autocommit: error (non-fatal): {e}", file=sys.stderr)
